[2024-01-18T22:45:28.326+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T22:45:28.335+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T22:45:28.335+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-18T22:45:28.352+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-16 23:56:00+00:00
[2024-01-18T22:45:28.355+0000] {standard_task_runner.py:57} INFO - Started process 314 to run task
[2024-01-18T22:45:28.358+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_data_batch_processing', 'submit_spark_job', 'scheduled__2024-01-16T23:56:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayer_dag.py', '--cfg-path', '/tmp/tmp5futjedb']
[2024-01-18T22:45:28.360+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask submit_spark_job
[2024-01-18T22:45:28.418+0000] {task_command.py:415} INFO - Running <TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [running]> on host 36e53310e6a3
[2024-01-18T22:45:28.512+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_data_batch_processing' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T23:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T23:56:00+00:00'
[2024-01-18T22:45:28.524+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-18T22:45:28.525+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py
[2024-01-18T22:45:28.703+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-01-18T22:45:28.704+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2024-01-18T22:45:28.719+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.
[2024-01-18T22:45:28.723+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_data_batch_processing, task_id=submit_spark_job, execution_date=20240116T235600, start_date=20240118T224528, end_date=20240118T224528
[2024-01-18T22:45:28.741+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task submit_spark_job (Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.; 314)
[2024-01-18T22:45:28.774+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-18T22:45:28.798+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-18T23:07:02.798+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T23:07:02.807+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T23:07:02.807+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-18T23:07:02.821+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-16 23:56:00+00:00
[2024-01-18T23:07:02.824+0000] {standard_task_runner.py:57} INFO - Started process 3740 to run task
[2024-01-18T23:07:02.831+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_data_batch_processing', 'submit_spark_job', 'scheduled__2024-01-16T23:56:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayer_dag.py', '--cfg-path', '/tmp/tmpyhro43ja']
[2024-01-18T23:07:02.832+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask submit_spark_job
[2024-01-18T23:07:02.889+0000] {task_command.py:415} INFO - Running <TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [running]> on host 36e53310e6a3
[2024-01-18T23:07:02.988+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_data_batch_processing' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T23:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T23:56:00+00:00'
[2024-01-18T23:07:02.998+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-18T23:07:02.999+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py
[2024-01-18T23:07:03.133+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-01-18T23:07:06.418+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-01-18T23:07:06.419+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 4, in <module>
[2024-01-18T23:07:06.419+0000] {spark_submit.py:571} INFO - from tensorflow.keras.models import load_model
[2024-01-18T23:07:06.419+0000] {spark_submit.py:571} INFO - ModuleNotFoundError: No module named 'tensorflow'
[2024-01-18T23:07:06.473+0000] {spark_submit.py:571} INFO - 24/01/18 23:07:06 INFO ShutdownHookManager: Shutdown hook called
[2024-01-18T23:07:06.475+0000] {spark_submit.py:571} INFO - 24/01/18 23:07:06 INFO ShutdownHookManager: Deleting directory /tmp/spark-263325e4-b4a2-4b29-8427-73626311c5c2
[2024-01-18T23:07:06.521+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.
[2024-01-18T23:07:06.524+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_data_batch_processing, task_id=submit_spark_job, execution_date=20240116T235600, start_date=20240118T230702, end_date=20240118T230706
[2024-01-18T23:07:06.539+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task submit_spark_job (Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.; 3740)
[2024-01-18T23:07:06.581+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-18T23:07:06.601+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-18T23:13:21.541+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T23:13:21.553+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T23:13:21.554+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-18T23:13:21.573+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-16 23:56:00+00:00
[2024-01-18T23:13:21.576+0000] {standard_task_runner.py:57} INFO - Started process 3867 to run task
[2024-01-18T23:13:21.582+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_data_batch_processing', 'submit_spark_job', 'scheduled__2024-01-16T23:56:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayer_dag.py', '--cfg-path', '/tmp/tmp2r0sqy2y']
[2024-01-18T23:13:21.584+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask submit_spark_job
[2024-01-18T23:13:21.663+0000] {task_command.py:415} INFO - Running <TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [running]> on host 36e53310e6a3
[2024-01-18T23:13:21.768+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_data_batch_processing' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T23:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T23:56:00+00:00'
[2024-01-18T23:13:21.780+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-18T23:13:21.781+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py
[2024-01-18T23:13:21.980+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-01-18T23:13:28.485+0000] {spark_submit.py:571} INFO - 2024-01-18 23:13:28.484746: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-01-18T23:13:28.631+0000] {spark_submit.py:571} INFO - 2024-01-18 23:13:28.630593: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:13:29.067+0000] {spark_submit.py:571} INFO - 2024-01-18 23:13:29.067556: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[2024-01-18T23:13:29.068+0000] {spark_submit.py:571} INFO - 2024-01-18 23:13:29.067654: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[2024-01-18T23:13:29.145+0000] {spark_submit.py:571} INFO - 2024-01-18 23:13:29.144737: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[2024-01-18T23:13:29.342+0000] {spark_submit.py:571} INFO - 2024-01-18 23:13:29.342632: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:13:29.344+0000] {spark_submit.py:571} INFO - 2024-01-18 23:13:29.344043: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-01-18T23:13:29.344+0000] {spark_submit.py:571} INFO - To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-01-18T23:13:31.831+0000] {spark_submit.py:571} INFO - 2024-01-18 23:13:31.831149: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-01-18T23:13:36.039+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-01-18T23:13:36.040+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 5, in <module>
[2024-01-18T23:13:36.040+0000] {spark_submit.py:571} INFO - from sklearn.preprocessing import MinMaxScaler
[2024-01-18T23:13:36.040+0000] {spark_submit.py:571} INFO - ModuleNotFoundError: No module named 'sklearn'
[2024-01-18T23:13:36.643+0000] {spark_submit.py:571} INFO - 24/01/18 23:13:36 INFO ShutdownHookManager: Shutdown hook called
[2024-01-18T23:13:36.648+0000] {spark_submit.py:571} INFO - 24/01/18 23:13:36 INFO ShutdownHookManager: Deleting directory /tmp/spark-3cbbe338-d754-4779-a352-373c1a38a807
[2024-01-18T23:13:36.735+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.
[2024-01-18T23:13:36.744+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_data_batch_processing, task_id=submit_spark_job, execution_date=20240116T235600, start_date=20240118T231321, end_date=20240118T231336
[2024-01-18T23:13:36.765+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task submit_spark_job (Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.; 3867)
[2024-01-18T23:13:36.777+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-18T23:13:36.799+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-18T23:32:46.812+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T23:32:46.827+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T23:32:46.827+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-18T23:32:46.850+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-16 23:56:00+00:00
[2024-01-18T23:32:46.856+0000] {standard_task_runner.py:57} INFO - Started process 4864 to run task
[2024-01-18T23:32:46.861+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_data_batch_processing', 'submit_spark_job', 'scheduled__2024-01-16T23:56:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayer_dag.py', '--cfg-path', '/tmp/tmp11bv_7qb']
[2024-01-18T23:32:46.866+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask submit_spark_job
[2024-01-18T23:32:46.961+0000] {task_command.py:415} INFO - Running <TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [running]> on host 36e53310e6a3
[2024-01-18T23:32:47.157+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_data_batch_processing' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T23:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T23:56:00+00:00'
[2024-01-18T23:32:47.182+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-18T23:32:47.184+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py
[2024-01-18T23:32:47.382+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-01-18T23:32:50.956+0000] {spark_submit.py:571} INFO - 2024-01-18 23:32:50.955759: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-01-18T23:32:50.958+0000] {spark_submit.py:571} INFO - 2024-01-18 23:32:50.957770: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:32:50.992+0000] {spark_submit.py:571} INFO - 2024-01-18 23:32:50.992455: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[2024-01-18T23:32:50.993+0000] {spark_submit.py:571} INFO - 2024-01-18 23:32:50.992532: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[2024-01-18T23:32:50.994+0000] {spark_submit.py:571} INFO - 2024-01-18 23:32:50.994034: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[2024-01-18T23:32:51.002+0000] {spark_submit.py:571} INFO - 2024-01-18 23:32:51.002371: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:32:51.002+0000] {spark_submit.py:571} INFO - 2024-01-18 23:32:51.002636: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-01-18T23:32:51.003+0000] {spark_submit.py:571} INFO - To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-01-18T23:32:52.076+0000] {spark_submit.py:571} INFO - 2024-01-18 23:32:52.075405: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-01-18T23:32:54.274+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SparkContext: Running Spark version 3.5.0
[2024-01-18T23:32:54.277+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SparkContext: OS info Linux, 5.10.102.1-microsoft-standard-WSL2, amd64
[2024-01-18T23:32:54.277+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SparkContext: Java version 11.0.21
[2024-01-18T23:32:54.330+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-01-18T23:32:54.408+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO ResourceUtils: ==============================================================
[2024-01-18T23:32:54.408+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-01-18T23:32:54.408+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO ResourceUtils: ==============================================================
[2024-01-18T23:32:54.409+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SparkContext: Submitted application: SparkDataStreaming
[2024-01-18T23:32:54.431+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-01-18T23:32:54.443+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO ResourceProfile: Limiting resource is cpu
[2024-01-18T23:32:54.443+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-01-18T23:32:54.490+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SecurityManager: Changing view acls to: ***
[2024-01-18T23:32:54.490+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SecurityManager: Changing modify acls to: ***
[2024-01-18T23:32:54.490+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SecurityManager: Changing view acls groups to:
[2024-01-18T23:32:54.491+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SecurityManager: Changing modify acls groups to:
[2024-01-18T23:32:54.491+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-01-18T23:32:54.738+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO Utils: Successfully started service 'sparkDriver' on port 32937.
[2024-01-18T23:32:54.770+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SparkEnv: Registering MapOutputTracker
[2024-01-18T23:32:54.807+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SparkEnv: Registering BlockManagerMaster
[2024-01-18T23:32:54.829+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-01-18T23:32:54.831+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-01-18T23:32:54.836+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-01-18T23:32:54.861+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-d4e346fc-f318-45ed-9d0d-c51739b6622a
[2024-01-18T23:32:54.882+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-01-18T23:32:54.899+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:54 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-01-18T23:32:55.049+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-01-18T23:32:55.104+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-01-18T23:32:55.213+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.29.0.5:7077...
[2024-01-18T23:32:55.261+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO TransportClientFactory: Successfully created connection to /172.29.0.5:7077 after 28 ms (0 ms spent in bootstraps)
[2024-01-18T23:32:55.387+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240118233255-0004
[2024-01-18T23:32:55.389+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240118233255-0004/0 on worker-20240118223130-172.29.0.7-36307 (172.29.0.7:36307) with 2 core(s)
[2024-01-18T23:32:55.395+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO StandaloneSchedulerBackend: Granted executor ID app-20240118233255-0004/0 on hostPort 172.29.0.7:36307 with 2 core(s), 1024.0 MiB RAM
[2024-01-18T23:32:55.396+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240118233255-0004/1 on worker-20240118223130-172.29.0.8-39635 (172.29.0.8:39635) with 2 core(s)
[2024-01-18T23:32:55.396+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO StandaloneSchedulerBackend: Granted executor ID app-20240118233255-0004/1 on hostPort 172.29.0.8:39635 with 2 core(s), 1024.0 MiB RAM
[2024-01-18T23:32:55.403+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40273.
[2024-01-18T23:32:55.403+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO NettyBlockTransferService: Server created on 36e53310e6a3:40273
[2024-01-18T23:32:55.405+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-01-18T23:32:55.414+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 36e53310e6a3, 40273, None)
[2024-01-18T23:32:55.420+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO BlockManagerMasterEndpoint: Registering block manager 36e53310e6a3:40273 with 434.4 MiB RAM, BlockManagerId(driver, 36e53310e6a3, 40273, None)
[2024-01-18T23:32:55.424+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 36e53310e6a3, 40273, None)
[2024-01-18T23:32:55.426+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 36e53310e6a3, 40273, None)
[2024-01-18T23:32:55.434+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20240118233255-0004/1 is now RUNNING
[2024-01-18T23:32:55.435+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20240118233255-0004/0 is now RUNNING
[2024-01-18T23:32:55.694+0000] {spark_submit.py:571} INFO - 24/01/18 23:32:55 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-01-18T23:32:55.988+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['cassandra'], lbp = None)
[2024-01-18T23:32:56.000+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 172.29.0.3:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-01-18T23:32:56.009+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 172.29.0.3:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-01-18T23:32:56.116+0000] {spark_submit.py:571} INFO - Keyspace created successfully!
[2024-01-18T23:32:56.119+0000] {spark_submit.py:571} INFO - Table created successfully!
[2024-01-18T23:32:56.120+0000] {spark_submit.py:571} INFO - Charger les données historiques depuis Cassandra
[2024-01-18T23:32:59.586+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-01-18T23:32:59.587+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 139, in <module>
[2024-01-18T23:32:59.588+0000] {spark_submit.py:571} INFO - batch_processing()
[2024-01-18T23:32:59.588+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 76, in batch_processing
[2024-01-18T23:32:59.588+0000] {spark_submit.py:571} INFO - historical_data = load_data_from_cassandra(spark_conn, "spark_streams", "historical_data")
[2024-01-18T23:32:59.588+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 12, in load_data_from_cassandra
[2024-01-18T23:32:59.589+0000] {spark_submit.py:571} INFO - df = spark.read.format("org.apache.spark.sql.cassandra") \
[2024-01-18T23:32:59.589+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 314, in load
[2024-01-18T23:32:59.590+0000] {spark_submit.py:571} INFO - return self._df(self._jreader.load())
[2024-01-18T23:32:59.590+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-01-18T23:32:59.590+0000] {spark_submit.py:571} INFO - return_value = get_return_value(
[2024-01-18T23:32:59.590+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-01-18T23:32:59.591+0000] {spark_submit.py:571} INFO - return f(*a, **kw)
[2024-01-18T23:32:59.591+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-01-18T23:32:59.591+0000] {spark_submit.py:571} INFO - raise Py4JJavaError(
[2024-01-18T23:32:59.591+0000] {spark_submit.py:571} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o31.load.
[2024-01-18T23:32:59.591+0000] {spark_submit.py:571} INFO - : org.apache.spark.SparkClassNotFoundException: [DATA_SOURCE_NOT_FOUND] Failed to find the data source: org.apache.spark.sql.cassandra. Please find packages at `https://spark.apache.org/third-party-projects.html`.
[2024-01-18T23:32:59.592+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.dataSourceNotFoundError(QueryExecutionErrors.scala:724)
[2024-01-18T23:32:59.592+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:647)
[2024-01-18T23:32:59.592+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:697)
[2024-01-18T23:32:59.592+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:208)
[2024-01-18T23:32:59.592+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
[2024-01-18T23:32:59.592+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-18T23:32:59.593+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-01-18T23:32:59.593+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-18T23:32:59.593+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-01-18T23:32:59.593+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-01-18T23:32:59.593+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-01-18T23:32:59.594+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-01-18T23:32:59.594+0000] {spark_submit.py:571} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-01-18T23:32:59.594+0000] {spark_submit.py:571} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-01-18T23:32:59.594+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-01-18T23:32:59.594+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-01-18T23:32:59.594+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-01-18T23:32:59.595+0000] {spark_submit.py:571} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.cassandra.DefaultSource
[2024-01-18T23:32:59.595+0000] {spark_submit.py:571} INFO - at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[2024-01-18T23:32:59.595+0000] {spark_submit.py:571} INFO - at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
[2024-01-18T23:32:59.595+0000] {spark_submit.py:571} INFO - at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
[2024-01-18T23:32:59.596+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:633)
[2024-01-18T23:32:59.596+0000] {spark_submit.py:571} INFO - at scala.util.Try$.apply(Try.scala:213)
[2024-01-18T23:32:59.596+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:633)
[2024-01-18T23:32:59.596+0000] {spark_submit.py:571} INFO - at scala.util.Failure.orElse(Try.scala:224)
[2024-01-18T23:32:59.596+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:633)
[2024-01-18T23:32:59.597+0000] {spark_submit.py:571} INFO - ... 15 more
[2024-01-18T23:32:59.597+0000] {spark_submit.py:571} INFO - 
[2024-01-18T23:33:01.086+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.
[2024-01-18T23:33:01.095+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_data_batch_processing, task_id=submit_spark_job, execution_date=20240116T235600, start_date=20240118T233246, end_date=20240118T233301
[2024-01-18T23:33:01.123+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task submit_spark_job (Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.; 4864)
[2024-01-18T23:33:01.147+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-18T23:33:01.177+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-18T23:37:57.608+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T23:37:57.618+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T23:37:57.619+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-18T23:37:57.638+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-16 23:56:00+00:00
[2024-01-18T23:37:57.643+0000] {standard_task_runner.py:57} INFO - Started process 5248 to run task
[2024-01-18T23:37:57.648+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_data_batch_processing', 'submit_spark_job', 'scheduled__2024-01-16T23:56:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayer_dag.py', '--cfg-path', '/tmp/tmpybd1hwqr']
[2024-01-18T23:37:57.650+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask submit_spark_job
[2024-01-18T23:37:57.733+0000] {task_command.py:415} INFO - Running <TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [running]> on host 36e53310e6a3
[2024-01-18T23:37:57.863+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_data_batch_processing' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T23:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T23:56:00+00:00'
[2024-01-18T23:37:57.879+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-18T23:37:57.880+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py
[2024-01-18T23:37:58.062+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-01-18T23:38:01.771+0000] {spark_submit.py:571} INFO - 2024-01-18 23:38:01.771219: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-01-18T23:38:01.774+0000] {spark_submit.py:571} INFO - 2024-01-18 23:38:01.774033: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:38:01.812+0000] {spark_submit.py:571} INFO - 2024-01-18 23:38:01.812280: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[2024-01-18T23:38:01.813+0000] {spark_submit.py:571} INFO - 2024-01-18 23:38:01.812352: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[2024-01-18T23:38:01.813+0000] {spark_submit.py:571} INFO - 2024-01-18 23:38:01.813740: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[2024-01-18T23:38:01.823+0000] {spark_submit.py:571} INFO - 2024-01-18 23:38:01.822869: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:38:01.823+0000] {spark_submit.py:571} INFO - 2024-01-18 23:38:01.823212: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-01-18T23:38:01.823+0000] {spark_submit.py:571} INFO - To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-01-18T23:38:03.189+0000] {spark_submit.py:571} INFO - 2024-01-18 23:38:03.189158: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-01-18T23:38:05.600+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO SparkContext: Running Spark version 3.5.0
[2024-01-18T23:38:05.603+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO SparkContext: OS info Linux, 5.10.102.1-microsoft-standard-WSL2, amd64
[2024-01-18T23:38:05.604+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO SparkContext: Java version 11.0.21
[2024-01-18T23:38:05.673+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-01-18T23:38:05.766+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO ResourceUtils: ==============================================================
[2024-01-18T23:38:05.766+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-01-18T23:38:05.766+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO ResourceUtils: ==============================================================
[2024-01-18T23:38:05.767+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO SparkContext: Submitted application: SparkDataStreaming
[2024-01-18T23:38:05.793+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-01-18T23:38:05.808+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO ResourceProfile: Limiting resource is cpu
[2024-01-18T23:38:05.809+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-01-18T23:38:05.871+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO SecurityManager: Changing view acls to: ***
[2024-01-18T23:38:05.872+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO SecurityManager: Changing modify acls to: ***
[2024-01-18T23:38:05.872+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO SecurityManager: Changing view acls groups to:
[2024-01-18T23:38:05.873+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO SecurityManager: Changing modify acls groups to:
[2024-01-18T23:38:05.873+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:05 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-01-18T23:38:06.106+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO Utils: Successfully started service 'sparkDriver' on port 38327.
[2024-01-18T23:38:06.139+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO SparkEnv: Registering MapOutputTracker
[2024-01-18T23:38:06.178+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO SparkEnv: Registering BlockManagerMaster
[2024-01-18T23:38:06.200+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-01-18T23:38:06.201+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-01-18T23:38:06.207+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-01-18T23:38:06.231+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-c1a9d861-4bba-4c6a-a7e0-106039c17906
[2024-01-18T23:38:06.246+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-01-18T23:38:06.265+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-01-18T23:38:06.441+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-01-18T23:38:06.508+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-01-18T23:38:06.644+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.29.0.5:7077...
[2024-01-18T23:38:06.717+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO TransportClientFactory: Successfully created connection to /172.29.0.5:7077 after 51 ms (0 ms spent in bootstraps)
[2024-01-18T23:38:06.974+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240118233806-0006
[2024-01-18T23:38:06.984+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41573.
[2024-01-18T23:38:06.998+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO NettyBlockTransferService: Server created on 36e53310e6a3:41573
[2024-01-18T23:38:06.999+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-01-18T23:38:06.999+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 36e53310e6a3, 41573, None)
[2024-01-18T23:38:06.999+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:06 INFO BlockManagerMasterEndpoint: Registering block manager 36e53310e6a3:41573 with 434.4 MiB RAM, BlockManagerId(driver, 36e53310e6a3, 41573, None)
[2024-01-18T23:38:07.003+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:07 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 36e53310e6a3, 41573, None)
[2024-01-18T23:38:07.005+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:07 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 36e53310e6a3, 41573, None)
[2024-01-18T23:38:07.191+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:07 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240118233806-0006/0 on worker-20240118223130-172.29.0.7-36307 (172.29.0.7:36307) with 2 core(s)
[2024-01-18T23:38:07.193+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:07 INFO StandaloneSchedulerBackend: Granted executor ID app-20240118233806-0006/0 on hostPort 172.29.0.7:36307 with 2 core(s), 1024.0 MiB RAM
[2024-01-18T23:38:07.205+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:07 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-01-18T23:38:07.216+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:07 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240118233806-0006/1 on worker-20240118223130-172.29.0.8-39635 (172.29.0.8:39635) with 2 core(s)
[2024-01-18T23:38:07.216+0000] {spark_submit.py:571} INFO - 24/01/18 23:38:07 INFO StandaloneSchedulerBackend: Granted executor ID app-20240118233806-0006/1 on hostPort 172.29.0.8:39635 with 2 core(s), 1024.0 MiB RAM
[2024-01-18T23:38:07.389+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['cassandra'], lbp = None)
[2024-01-18T23:38:07.717+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 172.29.0.3:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-01-18T23:38:07.942+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 172.29.0.3:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-01-18T23:38:08.233+0000] {spark_submit.py:571} INFO - Keyspace created successfully!
[2024-01-18T23:38:08.240+0000] {spark_submit.py:571} INFO - Table created successfully!
[2024-01-18T23:38:08.240+0000] {spark_submit.py:571} INFO - Charger les données historiques depuis Cassandra
[2024-01-18T23:38:11.252+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-01-18T23:38:11.253+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 139, in <module>
[2024-01-18T23:38:11.253+0000] {spark_submit.py:571} INFO - batch_processing()
[2024-01-18T23:38:11.253+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 76, in batch_processing
[2024-01-18T23:38:11.254+0000] {spark_submit.py:571} INFO - historical_data = load_data_from_cassandra(spark_conn, "spark_streams", "historical_data")
[2024-01-18T23:38:11.254+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 12, in load_data_from_cassandra
[2024-01-18T23:38:11.254+0000] {spark_submit.py:571} INFO - df = spark.read.format("org.apache.spark.sql.cassandra") \
[2024-01-18T23:38:11.254+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 314, in load
[2024-01-18T23:38:11.255+0000] {spark_submit.py:571} INFO - return self._df(self._jreader.load())
[2024-01-18T23:38:11.255+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-01-18T23:38:11.255+0000] {spark_submit.py:571} INFO - return_value = get_return_value(
[2024-01-18T23:38:11.255+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-01-18T23:38:11.256+0000] {spark_submit.py:571} INFO - return f(*a, **kw)
[2024-01-18T23:38:11.256+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-01-18T23:38:11.256+0000] {spark_submit.py:571} INFO - raise Py4JJavaError(
[2024-01-18T23:38:11.256+0000] {spark_submit.py:571} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o31.load.
[2024-01-18T23:38:11.256+0000] {spark_submit.py:571} INFO - : org.apache.spark.SparkClassNotFoundException: [DATA_SOURCE_NOT_FOUND] Failed to find the data source: org.apache.spark.sql.cassandra. Please find packages at `https://spark.apache.org/third-party-projects.html`.
[2024-01-18T23:38:11.257+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.dataSourceNotFoundError(QueryExecutionErrors.scala:724)
[2024-01-18T23:38:11.257+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:647)
[2024-01-18T23:38:11.257+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:697)
[2024-01-18T23:38:11.257+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:208)
[2024-01-18T23:38:11.257+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
[2024-01-18T23:38:11.257+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-18T23:38:11.257+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-01-18T23:38:11.258+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-18T23:38:11.258+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-01-18T23:38:11.258+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-01-18T23:38:11.258+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-01-18T23:38:11.258+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-01-18T23:38:11.258+0000] {spark_submit.py:571} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-01-18T23:38:11.259+0000] {spark_submit.py:571} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-01-18T23:38:11.259+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-01-18T23:38:11.259+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-01-18T23:38:11.259+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-01-18T23:38:11.259+0000] {spark_submit.py:571} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.cassandra.DefaultSource
[2024-01-18T23:38:11.259+0000] {spark_submit.py:571} INFO - at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[2024-01-18T23:38:11.260+0000] {spark_submit.py:571} INFO - at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
[2024-01-18T23:38:11.260+0000] {spark_submit.py:571} INFO - at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
[2024-01-18T23:38:11.260+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:633)
[2024-01-18T23:38:11.260+0000] {spark_submit.py:571} INFO - at scala.util.Try$.apply(Try.scala:213)
[2024-01-18T23:38:11.260+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:633)
[2024-01-18T23:38:11.260+0000] {spark_submit.py:571} INFO - at scala.util.Failure.orElse(Try.scala:224)
[2024-01-18T23:38:11.260+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:633)
[2024-01-18T23:38:11.261+0000] {spark_submit.py:571} INFO - ... 15 more
[2024-01-18T23:38:11.261+0000] {spark_submit.py:571} INFO - 
[2024-01-18T23:38:12.226+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.
[2024-01-18T23:38:12.230+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_data_batch_processing, task_id=submit_spark_job, execution_date=20240116T235600, start_date=20240118T233757, end_date=20240118T233812
[2024-01-18T23:38:12.245+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 37 for task submit_spark_job (Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.; 5248)
[2024-01-18T23:38:12.282+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-18T23:38:12.302+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-18T23:52:51.890+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T23:52:51.900+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [queued]>
[2024-01-18T23:52:51.901+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-18T23:52:51.918+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-16 23:56:00+00:00
[2024-01-18T23:52:51.922+0000] {standard_task_runner.py:57} INFO - Started process 5904 to run task
[2024-01-18T23:52:51.927+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_data_batch_processing', 'submit_spark_job', 'scheduled__2024-01-16T23:56:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayer_dag.py', '--cfg-path', '/tmp/tmpyrevhhoo']
[2024-01-18T23:52:51.928+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask submit_spark_job
[2024-01-18T23:52:51.988+0000] {task_command.py:415} INFO - Running <TaskInstance: bitcoin_data_batch_processing.submit_spark_job scheduled__2024-01-16T23:56:00+00:00 [running]> on host 36e53310e6a3
[2024-01-18T23:52:52.079+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_data_batch_processing' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T23:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T23:56:00+00:00'
[2024-01-18T23:52:52.092+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-18T23:52:52.092+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 474, in submit
    spark_submit_cmd = self._build_spark_submit_command(application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 401, in _build_spark_submit_command
    self.log.info("Spark-Submit cmd: %s", self._mask_cmd(connection_cmd))
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 305, in _mask_cmd
    " ".join(connection_cmd),
TypeError: sequence item 4: expected str instance, list found
[2024-01-18T23:52:52.108+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_data_batch_processing, task_id=submit_spark_job, execution_date=20240116T235600, start_date=20240118T235251, end_date=20240118T235252
[2024-01-18T23:52:52.127+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task submit_spark_job (sequence item 4: expected str instance, list found; 5904)
[2024-01-18T23:52:52.138+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-18T23:52:52.156+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
