[2024-01-18T23:25:16.869+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job manual__2024-01-18T23:25:12.350894+00:00 [queued]>
[2024-01-18T23:25:16.877+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job manual__2024-01-18T23:25:12.350894+00:00 [queued]>
[2024-01-18T23:25:16.878+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-18T23:25:16.894+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-18 23:25:12.350894+00:00
[2024-01-18T23:25:16.896+0000] {standard_task_runner.py:57} INFO - Started process 4414 to run task
[2024-01-18T23:25:16.900+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_data_batch_processing', 'submit_spark_job', 'manual__2024-01-18T23:25:12.350894+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayer_dag.py', '--cfg-path', '/tmp/tmpiceyaqv5']
[2024-01-18T23:25:16.902+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask submit_spark_job
[2024-01-18T23:25:16.975+0000] {task_command.py:415} INFO - Running <TaskInstance: bitcoin_data_batch_processing.submit_spark_job manual__2024-01-18T23:25:12.350894+00:00 [running]> on host 36e53310e6a3
[2024-01-18T23:25:17.077+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_data_batch_processing' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-18T23:25:12.350894+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-18T23:25:12.350894+00:00'
[2024-01-18T23:25:17.090+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-18T23:25:17.091+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py
[2024-01-18T23:25:17.243+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-01-18T23:25:22.677+0000] {spark_submit.py:571} INFO - 2024-01-18 23:25:22.677392: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-01-18T23:25:22.756+0000] {spark_submit.py:571} INFO - 2024-01-18 23:25:22.756158: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:25:23.105+0000] {spark_submit.py:571} INFO - 2024-01-18 23:25:23.105057: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[2024-01-18T23:25:23.106+0000] {spark_submit.py:571} INFO - 2024-01-18 23:25:23.105168: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[2024-01-18T23:25:23.212+0000] {spark_submit.py:571} INFO - 2024-01-18 23:25:23.212244: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[2024-01-18T23:25:23.402+0000] {spark_submit.py:571} INFO - 2024-01-18 23:25:23.401900: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:25:23.403+0000] {spark_submit.py:571} INFO - 2024-01-18 23:25:23.403214: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-01-18T23:25:23.404+0000] {spark_submit.py:571} INFO - To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-01-18T23:25:25.671+0000] {spark_submit.py:571} INFO - 2024-01-18 23:25:25.670405: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-01-18T23:25:30.081+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SparkContext: Running Spark version 3.5.0
[2024-01-18T23:25:30.083+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SparkContext: OS info Linux, 5.10.102.1-microsoft-standard-WSL2, amd64
[2024-01-18T23:25:30.084+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SparkContext: Java version 11.0.21
[2024-01-18T23:25:30.204+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-01-18T23:25:30.327+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO ResourceUtils: ==============================================================
[2024-01-18T23:25:30.328+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-01-18T23:25:30.328+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO ResourceUtils: ==============================================================
[2024-01-18T23:25:30.328+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SparkContext: Submitted application: SparkDataStreaming
[2024-01-18T23:25:30.356+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-01-18T23:25:30.370+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO ResourceProfile: Limiting resource is cpu
[2024-01-18T23:25:30.370+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-01-18T23:25:30.470+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SecurityManager: Changing view acls to: ***
[2024-01-18T23:25:30.470+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SecurityManager: Changing modify acls to: ***
[2024-01-18T23:25:30.471+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SecurityManager: Changing view acls groups to:
[2024-01-18T23:25:30.471+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SecurityManager: Changing modify acls groups to:
[2024-01-18T23:25:30.471+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-01-18T23:25:30.830+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO Utils: Successfully started service 'sparkDriver' on port 40941.
[2024-01-18T23:25:30.906+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SparkEnv: Registering MapOutputTracker
[2024-01-18T23:25:30.969+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:30 INFO SparkEnv: Registering BlockManagerMaster
[2024-01-18T23:25:31.007+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-01-18T23:25:31.008+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-01-18T23:25:31.012+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-01-18T23:25:31.060+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-c1b0e43a-9a3c-4f92-a563-4ce41acaec91
[2024-01-18T23:25:31.083+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-01-18T23:25:31.119+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-01-18T23:25:31.368+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-01-18T23:25:31.483+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-01-18T23:25:31.659+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.29.0.5:7077...
[2024-01-18T23:25:31.742+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO TransportClientFactory: Successfully created connection to /172.29.0.5:7077 after 49 ms (0 ms spent in bootstraps)
[2024-01-18T23:25:31.937+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240118232531-0002
[2024-01-18T23:25:31.937+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240118232531-0002/0 on worker-20240118223130-172.29.0.7-36307 (172.29.0.7:36307) with 2 core(s)
[2024-01-18T23:25:31.942+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO StandaloneSchedulerBackend: Granted executor ID app-20240118232531-0002/0 on hostPort 172.29.0.7:36307 with 2 core(s), 1024.0 MiB RAM
[2024-01-18T23:25:31.943+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240118232531-0002/1 on worker-20240118223130-172.29.0.8-39635 (172.29.0.8:39635) with 2 core(s)
[2024-01-18T23:25:31.990+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:31 INFO StandaloneSchedulerBackend: Granted executor ID app-20240118232531-0002/1 on hostPort 172.29.0.8:39635 with 2 core(s), 1024.0 MiB RAM
[2024-01-18T23:25:32.008+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:32 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41979.
[2024-01-18T23:25:32.009+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:32 INFO NettyBlockTransferService: Server created on 36e53310e6a3:41979
[2024-01-18T23:25:32.010+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:32 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20240118232531-0002/0 is now RUNNING
[2024-01-18T23:25:32.012+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:32 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-01-18T23:25:32.024+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:32 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 36e53310e6a3, 41979, None)
[2024-01-18T23:25:32.028+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:32 INFO BlockManagerMasterEndpoint: Registering block manager 36e53310e6a3:41979 with 434.4 MiB RAM, BlockManagerId(driver, 36e53310e6a3, 41979, None)
[2024-01-18T23:25:32.031+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:32 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 36e53310e6a3, 41979, None)
[2024-01-18T23:25:32.033+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:32 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 36e53310e6a3, 41979, None)
[2024-01-18T23:25:32.215+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:32 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20240118232531-0002/1 is now RUNNING
[2024-01-18T23:25:32.377+0000] {spark_submit.py:571} INFO - 24/01/18 23:25:32 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-01-18T23:25:33.095+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['cassandra'], lbp = None)
[2024-01-18T23:25:33.154+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 172.29.0.3:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-01-18T23:25:33.176+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 172.29.0.3:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-01-18T23:25:33.453+0000] {spark_submit.py:571} INFO - Keyspace created successfully!
[2024-01-18T23:25:33.466+0000] {spark_submit.py:571} INFO - Table created successfully!
[2024-01-18T23:25:36.224+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-01-18T23:25:36.225+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 132, in <module>
[2024-01-18T23:25:36.225+0000] {spark_submit.py:571} INFO - batch_processing()
[2024-01-18T23:25:36.226+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 75, in batch_processing
[2024-01-18T23:25:36.226+0000] {spark_submit.py:571} INFO - historical_data = load_data_from_cassandra(spark_conn, "spark_streams", "historical_data")
[2024-01-18T23:25:36.226+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 12, in load_data_from_cassandra
[2024-01-18T23:25:36.226+0000] {spark_submit.py:571} INFO - df = spark.read.format("org.apache.spark.sql.cassandra") \
[2024-01-18T23:25:36.226+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 314, in load
[2024-01-18T23:25:36.226+0000] {spark_submit.py:571} INFO - return self._df(self._jreader.load())
[2024-01-18T23:25:36.227+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-01-18T23:25:36.227+0000] {spark_submit.py:571} INFO - return_value = get_return_value(
[2024-01-18T23:25:36.227+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-01-18T23:25:36.227+0000] {spark_submit.py:571} INFO - return f(*a, **kw)
[2024-01-18T23:25:36.227+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-01-18T23:25:36.228+0000] {spark_submit.py:571} INFO - raise Py4JJavaError(
[2024-01-18T23:25:36.228+0000] {spark_submit.py:571} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o31.load.
[2024-01-18T23:25:36.228+0000] {spark_submit.py:571} INFO - : org.apache.spark.SparkClassNotFoundException: [DATA_SOURCE_NOT_FOUND] Failed to find the data source: org.apache.spark.sql.cassandra. Please find packages at `https://spark.apache.org/third-party-projects.html`.
[2024-01-18T23:25:36.228+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.dataSourceNotFoundError(QueryExecutionErrors.scala:724)
[2024-01-18T23:25:36.228+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:647)
[2024-01-18T23:25:36.228+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:697)
[2024-01-18T23:25:36.228+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:208)
[2024-01-18T23:25:36.228+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
[2024-01-18T23:25:36.228+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-18T23:25:36.229+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-01-18T23:25:36.229+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-18T23:25:36.229+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-01-18T23:25:36.229+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-01-18T23:25:36.229+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-01-18T23:25:36.229+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-01-18T23:25:36.229+0000] {spark_submit.py:571} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-01-18T23:25:36.229+0000] {spark_submit.py:571} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-01-18T23:25:36.230+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-01-18T23:25:36.230+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-01-18T23:25:36.230+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-01-18T23:25:36.230+0000] {spark_submit.py:571} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.cassandra.DefaultSource
[2024-01-18T23:25:36.230+0000] {spark_submit.py:571} INFO - at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[2024-01-18T23:25:36.230+0000] {spark_submit.py:571} INFO - at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
[2024-01-18T23:25:36.230+0000] {spark_submit.py:571} INFO - at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
[2024-01-18T23:25:36.230+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:633)
[2024-01-18T23:25:36.231+0000] {spark_submit.py:571} INFO - at scala.util.Try$.apply(Try.scala:213)
[2024-01-18T23:25:36.231+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:633)
[2024-01-18T23:25:36.231+0000] {spark_submit.py:571} INFO - at scala.util.Failure.orElse(Try.scala:224)
[2024-01-18T23:25:36.231+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:633)
[2024-01-18T23:25:36.231+0000] {spark_submit.py:571} INFO - ... 15 more
[2024-01-18T23:25:36.231+0000] {spark_submit.py:571} INFO - 
[2024-01-18T23:25:37.505+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.
[2024-01-18T23:25:37.512+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_data_batch_processing, task_id=submit_spark_job, execution_date=20240118T232512, start_date=20240118T232516, end_date=20240118T232537
[2024-01-18T23:25:37.530+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task submit_spark_job (Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.; 4414)
[2024-01-18T23:25:37.559+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-18T23:25:37.577+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
